### ISSUE TITLE
Remove need for manual passing of drizzle props in new context api components

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-react-components#100]
See if we can just bundle the Drizzle provider and consumer for users

**Comment by honestbonsai** [comment]
If this is possible, it should be the default components exported in 2.0. The base ones that require manual prop passing of `drizzle` should be under a different namespace.

**Comment by adrianmcli** [comment]
@honestbonsai Is this fixed with the ability to do the `Class.contextType` [pattern](https://reactjs.org/docs/context.html#classcontexttype) with Drizzle-React [1.3.0](https://github.com/trufflesuite/drizzle-react/releases/tag/1.3.0)?
