### ISSUE TITLE
Trouble sendArgs with transfer method

### ISSUE THREAD

**Issue by Chanutg** [trufflesuite/drizzle-react-components#105]
Hello i'm looking to make a transfert with adress and value setup, in order to just click on a button for the user to buy something with token.

I use a ContractForm, working well if adresse and value set by user, but sendArgs is not working.
Here is my form :

                  <ContractForm
                    contract="Influence"
                    method="transfer"
                    methodArgs={{to: "0xbd85593F294f953dC67dBDd4C34Ff7cd8681156A", value: 5}}
                  />

**Comment by adrianmcli** [comment]
@honestbonsai Do you mind taking a look at this when you have the time?

**Comment by adrianmcli** [comment]
@chanutg Can you provide us a reproduction repo for this bug?
