### ISSUE TITLE
ContractData: does not work for mappings

### ISSUE THREAD

**Issue by djudjuu** [trufflesuite/drizzle-react-components#11]
When wanting to display a contracts mapping, such as 
`mapping (uint => bool) public isCoolNumber;`

with 
 `ContractData contract="SimpleStorage" method="cool"  methodArgs={[8]}`

i get
`utils.js:240 uncaught at l TypeError: e.slice is not a function`

I tried this by adjusting the drizzle-box.

**Comment by honestbonsai** [comment]
Just FYI: https://solidity.readthedocs.io/en/v0.5.5/types.html#mapping-types

And https://ethereum.stackexchange.com/questions/13167/are-there-well-solved-and-simple-storage-patterns-for-solidity

**Comment by DiscRisknBisque** [comment]
Try passing in 8 as an integer instead, like so:
`ContractData contract="SimpleStorage" method="cool" methodArgs={8}`

Based on the `slice` message, I think web3 doesn't know what to do with the array for accessing this mapping.
