### ISSUE TITLE
ContractData: Address Array is not shown

### ISSUE THREAD

**Issue by tkddn204** [trufflesuite/drizzle-react-components#15]
I just use this code, but I can't show address type data list...
```
import React, {Component} from 'react'
import { AccountData, ContractData, ContractForm} from 'drizzle-react-components'

class Home extends Component {
    render() {
        return (
            <main className="container">
                        ...
                        <h2>VoteFactory</h2>

                        <strong>현재 생성된 투표 개수</strong>:
                        <ContractData contract="VoteFactory" method="getDeployedVotesLength"/>

                        <br/><br/>

                        <strong>현재 생성된 투표 목록</strong>:
                        <ContractData contract="VoteFactory" method="getDeployedVotes" />
                        ...
            </main>
        )
    }
}

export default Home
```

And My contract Code is here:
```
    function getDeployedVotes() external view returns (address[]) {
        return deployedVotes;
    }

    function getDeployedVotesLength() external view returns (uint) {
        return deployedVotes.length;
    }
```

This is result page:
![result page](https://user-images.githubusercontent.com/6284140/39168489-0aa97256-47cf-11e8-9475-d43fff5ed733.png)

Contract codes already success Compile and Migration,
I also used properties of `toUtf8`, `toAscii`, It is not working.
How can I solve this?

**Comment by St3fanoC** [comment]
I have the same error with the arrays of address in the version 1.2 of this library.
On line 59 of ContractData.js there is this condition: if (typeof displayData === 'array'),  I did various tests and noticed that if you use typeof on an array it always returns false.
I think the control is to be changed in Array.isArray (displayData).
I'm not a javascript black belt and I apologize if I said bullshit and would like to receive a correction :)
