### ISSUE TITLE
ContractForm does not work correctly with Bool type method argument

### ISSUE THREAD

**Issue by sevriugin** [trufflesuite/drizzle-react-components#16]
I am calling vote method in Contract Form
```
<ContractForm contract="LCSToken" method="vote" labels={['NFT Token ID','Positive?']} />
```
and the second argument always receive FALSE as a value, so the voting result is negative
There is my contract method :
```
 function vote(uint256 _id, bool _positive) public {
        require(_id != uint256(0));
        require(_id == voters[msg.sender]);
        require(extensions[_id].status == uint8(Status.Claim));
        Request storage _request = requests[_id];
        uint votingEnd = _request.timeStamp + _request.duration;
        require(votingEnd >= now);

        if(_positive) {
            _request.positive++;
        } else {
            _request.negative++;
        }
        delete voters[msg.sender]; // deliting prevent the second time voting
        // emit event
        Vote(msg.sender, _id, _positive);
    }
```

**Comment by DanielArndt** [comment]
Did #24 work as intended? I have version 1.2.0 of `drizzle-react-components` and it seems like it was transpiled out. 

I have very little familiarity with most of the tools (`react`, `babel`, `drizzle`) so I'm struggling to debug any further, but I was able to trace it down to these lines of code in my `drizzle-react-components.js` (transpiled?) code:

```javascript
      return _react2.default.createElement(
        'span',
        null,
        displayData,
        pendingSpinner
      );
```

In the above code, while running in my project, `displayData` is still a boolean, and not a string.

It seems like the template literal was ignored here: https://github.com/mnaamani/drizzle-react-components/blob/fd3f07ffd3b7caaae919ec4ed07ed62c381a6704/src/ContractData.js#L104

I'm happy to debug further / attempt a fix, but I'm slow to understand how all this `webpack` / `babel` stuff is getting in my way. Or maybe it is something I am doing wrong.

**Comment by DanielArndt** [comment]
Seems when I clone this repo and run `npm run build` I get different output:

```javascript
return __WEBPACK_IMPORTED_MODULE_1_react___default.a.createElement(
  'span',
  null,
  `${displayData}`,
  pendingSpinner
);
```
