### ISSUE TITLE
ContractForm should be able to send value for interaction with payable methods

### ISSUE THREAD

**Issue by bgits** [trufflesuite/drizzle-react-components#17]
A common use case to is to send Eth to a contract for example wrapped-eth (https://weth.io/).

Currently this will not work as the `deposit` method is a payable with no arguments and the methodArgs does not exist for this component.

`<ContractForm contract="WrappedEth" method="deposit" methodArgs={[{value: 1000000}]}/>`

The preferred implementation would probably be to display an input field when a payable method is detected.

**Comment by nickreynolds** [comment]
This seems incredibly important. Can we get this functionality added soon?

**Comment by bellaj** [comment]
me too i don't think why it's a missing feature, value field is recognized though!!!

**Comment by bellaj** [comment]
based on @MoreSpaceThanMatter I've edited drizzle pakage to enable sending weis using a value field as in web3js 
https://github.com/trufflesuite/drizzle-react-components/pull/23

**Comment by honestbonsai** [comment]
Similar to #2

**Comment by mwaeckerlin** [comment]
IMHO, this ticket can be closed, @honestbonsai:
 - there is now `sendArgs`, where a value can be given
 - as you, @honestbonsai, demonstrated, with a sate in the parent and the new `render` prop, even a dynamical adaption, i.e. get the value from an input field, can be covered
