### ISSUE TITLE
ContractForm: Argument ordering of cacheSend in handleSubmit is arbitrary

### ISSUE THREAD

**Issue by mnaamani** [trufflesuite/drizzle-react-components#25]
When submitting the form, the ordering of arguments to cacheSend method:

`method.cacheSend(...Object.values(this.state))`

...are not guaranteed to be in the correct order:

Object.values iterates over the state keys in the same order as for...in  which iterates over the properties of an object in an [arbitrary order](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

The only case where this implementation is bug free is in the case that less than two arguments are expected by the contract method.

We need a custom method to generate the arguments in correct order.

**Comment by honestbonsai** [comment]
Closing since issues have been addressed by recent PRs.
