### ISSUE TITLE
Created Drizzle-react-components-plus

### ISSUE THREAD

**Issue by ProphetDaniel** [trufflesuite/drizzle-react-components#32]
Solves most of the problems of drizzle-react-components.
Mainly:

- Lack of ContractParameterizableData
- Lack of ContractAllData
- Spinner for Account balance
- Input form for optional txParams

More information here: https://github.com/ProphetDaniel/drizzle-react-components-plus
I would be happy to see these improvements here.

**Comment by honestbonsai** [comment]
@ProphetDaniel Thanks for the improvements and suggestions, we'll definitely take a look. Sorry for the long delay.
