### ISSUE TITLE
React components render method always repaint

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/drizzle-react-components#33]
All the react components force a render/repaint even if state or props haven't changed.

[Gyazo Link](https://gyazo.com/ed71eb4bc67e349c067781559cfbf713) showing the issue

The components could each implement [shouldComponentUpdate()](https://developmentarc.gitbooks.io/react-indepth/content/life_cycle/update/using_should_component_update.html) to opt-out of the update. However, is this the best way forward though? Could this be done further up the drizzle stream? Please comment.

Repo to reproduce: [drizzle-react-starter branch: render-slam](https://github.com/cds-amal/drizzle-react-starter/tree/render-slam)

**Comment by ijxy** [comment]
@cds-amal I agree this is a problem. The drizzle-react documentation discusses a new DrizzleContext API for React Context v16.3+. The components given here currently are actually written to the legacy API (i.e. ≤ v16.3). I have submitted #37 with implementations following the new standards - I'm hopeful that this is a 'further up the stream' fix. Based on my testing, it seems to be; whereas `console.log` statements previously printed non-stop, they now only print when an update is made.

**Comment by cds-amal** [comment]
Thank you @parkinsonj!  PR #37 closes this.
