### ISSUE TITLE
ContractData does not support array of objects response

### ISSUE THREAD

**Issue by ilanolkies** [trufflesuite/drizzle-react-components#35]
I'm trying to use a `ContractData` to query a method which response is
```js
[ BigNumber { s: 1, e: 0, c: [ 0 ] },
  '0x0000000000000000000000000000000000000000',
  BigNumber { s: 1, e: 0, c: [ 0 ] } ]
```

This type of object is not supported to be displayed: objects inside a list.

https://github.com/trufflesuite/drizzle-react-components/blob/2dda732ab9ce17e19693495647048f7b62de6aaf/src/ContractData.js#L60

It should display the structures recursively.

**Comment by honestbonsai** [comment]
@ilanolkies This looks to be the same as #6, which just got closed. Please reopen if you still experience issues.

**Comment by ilanolkies** [comment]
Thanks. I'll test it ASAP
