### ISSUE TITLE
ContractData does not update when it's props change

### ISSUE THREAD

**Issue by fl0ster** [trufflesuite/drizzle-react-components#4]
I would expect ContractData component to update it's content when one of it's props value is changed. Instead it remains fixed with data it received on application load.

I submitted a pull request that solved the issue for me.

**Comment by tcz001** [comment]
hi, could this be merged?

**Comment by honestbonsai** [comment]
Seems to be the same as #13, closing this one since the other one has more activity. Please reopen if I got it wrong.
