### ISSUE TITLE
Discussion: Usage with new Consumer API

### ISSUE THREAD

**Issue by soundyogi** [trufflesuite/drizzle-react-components#51]
Hiya,
this is not really an issue but I started refactoring the react-components to be used via the context.consumer pattern ( and to work with react-native and web if possible ).

My experience was fun but a bit strange so I wanted to share, cause it does feel a bit weird to me.
I came up with the following to call contract methods for example:

Usage Example:
```
class Story extends React.Component {
  private walletContract = React.createRef()

  render(){
    return (
      <DrizzleContext.Provider drizzle={storeDrizzle()}>
      
        {/* I feel weird using the component as API using a ref */}
        <ContractSend contractName={'Wallet'} ref={this.walletContract}/> 

        <button onClick={ () => this.walletContract.current.send('deposit', {amount: 10}) }>Deposit</button> 
        <button onClick={ () => this.walletContract.current.send('withdraw', {amount: 10}) }>Withdraw</button> 

      </DrizzleContext.Provider>
    )
  }
}
```

Implementation:
https://gist.github.com/soundyogi/8eac4a67b820e6ea2f9635301fd2fa66

Problems:
I could not get it to work packages as a library, which is proibably due to how ReactContext works (not the same context), or due to the packaging with webpack.

How are you using drizzle via the new consumer pattern?
Cheers.

**Comment by honestbonsai** [comment]
@soundyogi I believe #63 should solve your issues? Seems like you're talking about the new Context support?

**Comment by soundyogi** [comment]
Yes, to be specific I opened this Issue because I am having problems finding good patterns to use the new api.

I am pretty happy with the Abstraction above for sending transactions.
I also wrote another component called "ContractFetch" which is the preferred way of using the Context API. 

It fetches all method data and renders a passed component as soon as all data has been fetched.

API:
```
export const Wrapper = () => {
  const contractName = 'MyContract'

  const parseToPercentage = (x) => (parseInt(x) / 1000)

  const methods = {
    'methodA': {}, 
    'methodB': { parse: parseToPercentage }, 
    'methodC': { parse: parseToPercentage },  
    'balanceOf': { parse: parseInt, methodArgs: [web3.eth.accounts.givenProvider.selectedAddress] },
    'methodD': { parse: parseInt, methodArgs: [web3.eth.accounts.givenProvider.selectedAddress] }
  }

  return <ContractFetch contractName={contractName} methods={methods} component={MyComponent} consumer={DrizzleContext.Consumer}/>
}
```

The Main issue with abstracting the context api is that you have to pass 'Context'.

Feel Free to Close this Issue if no one else has problems, but I am finding working with the new React Context API is weird thats why I wanted to start a discussion.

My Goal basically is that I dont have to wrap my Components in Drizzle.Consumer all the time.

I updated the `ContractSend` component aswell:

```
[...]
        <ContractSend contractName={'MyContract'} ref={this.myRef} context={DrizzleContext} />
        <Button onClick={ () =>  that.myRef.current.send('myMethodName', myArgs) }>Click</Button> 
[...]
```

As Far as I am Concerned, my `ContractSend` and `ContractFetch` Components could replace all of the drizzle-react-components we have at this moment.

**Comment by honestbonsai** [comment]
Hmm yea, I'm not a huge fan on how we need to wrap the components in the Consumer all the time either. I wonder if they could be bundled with the component itself.

@soundyogi Seems like you're advocating for a more generalized approach with regards to the components?

**Comment by soundyogi** [comment]
@honestbonsai

Yes , we have been experimenting with this the last weeks and I came up with 1 Component that uses the consumer internally. Handling data caching aswell as transactions. As you said, The Problem is that you have to give it the correct instance of "context", so the component has to receive it as a prop.

So far we could replace all the drizzle-react-components with this single one.
The component also mounts the contract and deletes it if gets unmounted. (Which is much nicer than a centralized config, if you ask me, but we also have a lot of different contracts)

Currently it only supports a single Contract. (Its gets complicated if you need more than one contracts data)

Maybe the webpack build could include drizzle-react as a external dependency so we maybe would not need to pass the context as a prop. Since then the context instance should be the same, if its not included in the conponent library.

But,

i have the feeling that the new hooks api is much nicer to work with. This is not a drizzle problem but just the way the new react context system works. (I find it uncomfortable still)

So I think all of this kinda was for nothing since the hooks api seems to be much nicer.

I have to experiment with that though.

But yes I think a single Component could handle all the needs that drizzle-react-component provides and (kinda) hide the consumer.

I can upload it as a gist if you are interested. I am closing this for now since I am not really happy with any of the solutions we came up with.

**Comment by adrianmcli** [comment]
I was wondering, maybe we could use the `Class.contextType` API to make things a little less verbose? The function as a child pattern is good, but can be a little verbose when we need to use it in a lot of different components.

A similar issue was discussed here: https://github.com/trufflesuite/drizzle-react/issues/57#issuecomment-487863777

**Comment by soundyogi** [comment]
@adrianmcli 
Uh I did not know that. I like that one.
That still does not solve the problem if you want to abstract the whole thing away.
But that probably could be fixed with a webpack build that marks the drizzle-react lib as external dependency. So the context should be the same - and the user would only need to use the provider.

This is the last iteration of our <Contract/> Component which handles Contract mounting and sending transactions.

```export class DrizzleContainer extends React.Component {
  public render() {

    const methods = {
      methodCallA: {
        method: 'myMethod'
      },
      methodCallB: {
        method: 'myMethod',
        methodArgs: []
      }
    }

    const contractConfig = {
      contractName: 'MyContract',
      web3Contract: new web3.eth.Contract(
        Artifact.abi, Addr
      )
    }

    const contractEvents = [
      {
        eventName: 'EventA',
        eventOptions: {
          fromBlock: 0,
        }
      },
      {
        eventName: 'EventB',
        eventOptions: {
          fromBlock: 0,
        }
      }
    ]

    return <Contract
      contractConfig={contractConfig}
      contractEvents={contractEvents}
      cacheMethods={methods}
      component={MyComponent}
      context={DrizzleContext}
      mount
    />
  }
}
```

The Only thing bothering me is that the user has to pass the Context as prop.
