### ISSUE TITLE
ContractForm: bool types (checkboxes) do not set value

### ISSUE THREAD

**Issue by samajammin** [trufflesuite/drizzle-react-components#53]
I had a form input that included a boolean argument (`isAdmin`):
```
<ContractForm
  contract="SimpleDemocracy"
  method="registerVoter"
  labels={['Address', 'isAdmin']}
/>
```
Contract code:
```
function registerVoter(address voter, bool _isAdmin) public isAdmin() {
    require(getRegistration(voter) == false, "Voter already registered.");
    voters[voter] = Voter({ hasRegistered: true, isAdmin: _isAdmin});
}
```
Regardless of if the `isAdmin` checkbox was checked or not, the record would save as `false`. Logging `this.state` in `handleSubmit()` of ContractForm.js revealed that my `isAdmin` value was always being set to an empty string.

PR fix coming...

**Comment by adrianmcli** [comment]
Let's keep this open for now since there is a PR in-review (although admittedly it is long overdue).

**Comment by samajammin** [comment]
@adrianmcli I believe this can be closed now that https://github.com/trufflesuite/drizzle-react-components/pull/54 is merged

**Comment by adrianmcli** [comment]
Thanks @sbrichards
