### ISSUE TITLE
ContractData: Bug in displayData array type check and rendering

### ISSUE THREAD

**Issue by latenssi** [trufflesuite/drizzle-react-components#6]
I am pretty sure that in [ContractData.js#L68](https://github.com/trufflesuite/drizzle-react-components/blob/master/src/ContractData.js#L68) the check whether the *displayData* object is an array or not is incorrect. 

The correct would be: ` if (displayData instanceof Array) `.

**Comment by latenssi** [comment]
There was also a bug in the rendering of the array. 

I have combined a fix for both issues in PR #7.

**Comment by chunkzer** [comment]
I just ran into this. Good work and thank you for the fix @latenssi, hopefully it gets merged soon.

**Comment by honestbonsai** [comment]
Closed by #46
