### ISSUE TITLE
Add AccountData to README

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-react-components#65]
AccountData is missing from README

**Comment by mwaeckerlin** [comment]
i.e, add to Readme: How do I get the *balance* not only of the user's account, but also of a *contract*? [Some](https://itnext.io/how-to-use-drizzle-truffle-and-react-to-make-the-best-front-end-for-your-ethereum-dapp-ee09c8e94eae) pretend by using method `balanceOf`, but that's a lie, that results in `Uncaught TypeError: Cannot read property 'cacheCall' of undefined`.
