### ISSUE TITLE
Custom formatter props for ContractData?

### ISSUE THREAD

**Issue by jklepatch** [trufflesuite/drizzle-react-components#71]
Could we add a prop to specify a custom formatter function for `<ContractData />`? For example, it could be useful for Ether amounts.

**Comment by honestbonsai** [comment]
@jklepatch Not sure if I'm understanding you correctly. Can you provide an example api of what you're looking for?

**Comment by honestbonsai** [comment]
@jklepatch Can you confirm if this was resolved by #81 and its custom render props?

**Comment by jklepatch** [comment]
Yes it is

**Comment by honestbonsai** [comment]
Thanks! Closing.
