### ISSUE TITLE
Add Documentation to README, How To Get Contract Balance

### ISSUE THREAD

**Issue by mwaeckerlin** [trufflesuite/drizzle-react-components#72]
Please add an information to the README, how to get contract balance using drizzle components.

Or does it need a new component? If yes, then please consider this as a feature request.

**Comment by honestbonsai** [comment]
@mwaeckerlin 

Recently added test apps to the repo, so you can feel free to pull it and see all the features of `drizzle-react-components` and how to implement them.

Take a look at this line in the `test-app`.

https://github.com/trufflesuite/drizzle-react-components/blob/master/test-app/app/src/MyComponent.js#L74

Closing this. Please reopen if you still have issues with this.

**Comment by mwaeckerlin** [comment]
**No**, @honestbonsai, that is not what I mean! The line shows, how to call a method `balanceOf` in a `TutorialToken`. What I need is to get the balance of a **contract**.

That's what you get, when you call `drizzle.web3.eth.getBalance(contractAddress)`.

Currently, I use this workaround:
```
  async balance() {
    if (this.ready()) {
      const balance = await this.drizzle.web3.eth.getBalance(
        this.drizzle.contracts.ContractName.options.address
      );
      this.store.dispatch(actions.setContractNameBalance(balance));
      setTimeout(this.balance, 20000); // update every 20s
    } else setTimeout(this.balance, 500); // retry in ½s
  }
```

Please reopen the ticket!

**Comment by honestbonsai** [comment]
@mwaeckerlin Sorry for mistakenly closing it and thanks for the clarification.

This is indeed a feature request, none of the current components will do what you are looking for.

**Comment by mwaeckerlin** [comment]
Thank you, @honestbonsai. Any chance to get an implementation soon?

BTW: Is there any discussion group on the library? I had other questions, e.g. how to cope with maps and arrays. I've seen in the code, that there is a mapping to html-lists, but how and what are the preconditions?

**Comment by honestbonsai** [comment]
@mwaeckerlin I can't promise an implementation for this feature immediately, as there are a number of other things I'm working on at the moment. We do welcome PRs from the community.

As far as discussion group and community, you can go to [Spectrum](https://spectrum.chat/trufflesuite) for general support, GitHub for diagnosed errors or specific feature discussion, and [Reddit](https://www.reddit.com/r/ethdev/) for general discussion.

**Comment by mwaeckerlin** [comment]
Opened a feature request in #88.
