### ISSUE TITLE
Test apps still have issue with 1.3

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-react-components#85]
Brought up in #81 

https://github.com/trufflesuite/drizzle-react-components/pull/81#issuecomment-472190822

**Comment by honestbonsai** [comment]
Tested again, and it works. Not sure what the issue is here.

**Comment by cds-amal** [comment]
@honestbonsai , I found no issues running with `ganache ui` and `truffle develop`

**Comment by honestbonsai** [comment]
Thanks @cds-amal ! 

In that case I will be closing this issue. I think Metamask could be the culprit. Another option is to disable/uninstall Metamask then re-enable/install it again to get the test apps working. (Yes, annoying I know.)
