### ISSUE TITLE
Nightly Development Builds

### ISSUE THREAD

**Issue by mwaeckerlin** [trufflesuite/drizzle-react-components#91]
Please add a nightly npm-release for the latest drizzle develop branch.

Reasons:
- It would be handy for developers to be able to rely on the latest features, without having to clone and build the project on their own.
- The current latest release, 1.3.1, is very outdated: no «new» interface, non-working arrays, missing render props

BTW: It would be time for a new release. The current deveopment version runs stable AFAIK. The only reason I see, what would need to be fixed before a release, would be some warnings that need to be eliminated first, see #90.

**Comment by mwaeckerlin** [comment]
@gnidan, status?

**Comment by mwaeckerlin** [comment]
@honestbonsai, what about releasing a new version `1.4.0` containing the recent changes regarding `render`?

**Comment by honestbonsai** [comment]
@mwaeckerlin I'm looking to get #97 resolved before 1.4.0 is released.

**Comment by mwaeckerlin** [comment]
still TBD

**Comment by adrianmcli** [comment]
Just an update on this. We are in the process of moving this repo and the other Drizzle-related repos into a monorepo so that we can orchestrate this better.
