### ISSUE TITLE
Refactor deps in package.json

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-react-components#92]
Refer to:

1. https://github.com/trufflesuite/drizzle-react-components/blob/develop/webpack.prod.js#L34
1. https://webpack.js.org/configuration/externals/

We rely on the versions in the users' app. So I'm pretty sure having https://github.com/trufflesuite/drizzle-react-components/blob/develop/package.json#L25 isn't proper. If anything it should be moved to `devDependencies`.

**Comment by adrianmcli** [comment]
@honestbonsai wait, isn't this supposed to be a `peerDependency`?

**Comment by honestbonsai** [comment]
@adrianmcli Yea true, that's probably the correct place for it

**Comment by adrianmcli** [comment]
We need to do this.
