### ISSUE TITLE
Deprecate legacy context components

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-react-components#93]
This will require a 2.0 release.

**Comment by cds-amal** [comment]
We should coordinate with an updated release of truffle boxes to use the newer 2.0 API

**Comment by adrianmcli** [comment]
I believe a lot of people are still not satisfied with the new context API (for better or worse). I think we should still continue supporting the legacy context components in the mean time. Thoughts? @cds-amal @honestbonsai

**Comment by honestbonsai** [comment]
@adrianmcli I understand the "meantime" to mean pre-v2.0, while we figure out the best implementation for the new context api components for v2.0. So as long as we don't release 2.0 we will support it is my thoughts. I've always seen 1.x as a staging ground to get feedback on the appropriate API for them, and 2 would solidify them.

#100 is partly related to this
