### ISSUE TITLE
Improve api for translateType for custom render in ContractForm

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-react-components#97]
I'm not a huge fan of the translateType interface in `ContractForm`'s custom render, would be good to just send it down with `this.inputs` somehow.

Though I don't want to mutate `this.inputs`

**Comment by adrianmcli** [comment]
What exactly does `translateType` do? I don't see any documentation for it.

**Comment by honestbonsai** [comment]
With the custom rendered components for `ContractForm`, need to figure out a better way to send down the types.

See the current state:
https://github.com/trufflesuite/drizzle-react-components/blob/develop/test-app/app/src/MyComponent.js#L14

Also see the default render version
https://github.com/trufflesuite/drizzle-react-components/blob/develop/src/new-context-api/ContractForm.js#L61

**Comment by honestbonsai** [comment]
I have an idea of what to do for this.
